# Generated by Django 6.0.3 on 2026-04-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductAdmin",
        ),
    ]
