# Generated by Django 6.0.3 on 2026-04-09 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
        ("product", "0002_delete_productadmin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="market",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="market.market",
            ),
        ),
    ]
