# Generated by Django 6.0.3 on 2026-04-09 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_market"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="badge",
            field=models.CharField(
                choices=[
                    ("hot", "Hot"),
                    ("top pick", "Top Pick"),
                    ("best seller", "Best Seller"),
                ],
                default="best seller",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="original_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.FloatField(
                default=1,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
