# Generated by Django 6.0.3 on 2026-04-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_product_badge_product_original_price_product_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Images/"),
        ),
    ]
