# Generated by Django 6.0.3 on 2026-04-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="original_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
