# Generated by Django 6.0.3 on 2026-04-18 04:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
        ("user", "0003_remove_userprofile_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="date",
        ),
        migrations.AddField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="user.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(
                choices=[
                    ("ORDER_UPDATE", "Order Update"),
                    ("PROMOTION", "Promotion"),
                    ("SYSTEM_ALERT", "System Alert"),
                ],
                max_length=200,
            ),
        ),
    ]
