# Generated by Django 6.0.3 on 2026-04-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notification_date_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(choices=[('ORDER_UPDATE', 'Order Update'), ('PROMOTION', 'Promotion'), ('SYSTEM_ALERT', 'System Alert')], default='SYSTEM_ALERT', max_length=200),
        ),
    ]
