# Generated by Django 6.0.3 on 2026-04-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserProfile",
        ),
    ]
