# Generated by Django 6.0.3 on 2026-04-18 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_rename_user_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="notification",
        ),
    ]
